<?php
/**
 * This file is part of the Itabs_CustomSku module.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @category  Itabs
 * @package   Itabs_CustomSku
 * @author    ITABS GmbH <info@itabs.de>
 * @copyright 2015 ITABS GmbH (http://www.itabs.de)
 */
/**
 * @var $this Itabs_CustomSku_Block_Info
 */
?>
<?php if ($_customSku = $this->getCustomSku()): ?>
    <div class="checkout-custom-sku">
        <span class="label"><?php echo $this->__('Your custom SKU:'); ?></span> <?php echo $this->escapeHtml($_customSku); ?>
    </div>
<?php endif; ?>
